# Site settings
# title: xxx
title: CrzyJcky
description: Connecting Ideas

baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://crzyjcky.com" # the base hostname & protocol for your site
twitter_username: crzyjcky
github_username:  crzyjcky

# Build settings
markdown: kramdown

kramdown:
  input: GFM

#markdown: redcarpet
#markdown_ext: markdown,mkdown,mkdn,mkd,md

#redcarpet:
#  extensions: ["tables", "autolink", "strikethrough", "space_after_headers", "with_toc_data", "fenced_code_blocks"]
